// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3JPBhyK31JXlVkA4qjKJCh9I7yCddCaU',
    appId: '1:332395809937:web:dc21daf3e450a81a77c330',
    messagingSenderId: '332395809937',
    projectId: 'gossipapp-6c440',
    authDomain: 'gossipapp-6c440.firebaseapp.com',
    storageBucket: 'gossipapp-6c440.appspot.com',
    measurementId: 'G-51YL25YERB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTcG7RcgsedVwjGzY0sAzTNOkVLOQ9-RQ',
    appId: '1:332395809937:android:9adf29420cf4cbd077c330',
    messagingSenderId: '332395809937',
    projectId: 'gossipapp-6c440',
    storageBucket: 'gossipapp-6c440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1YqMP2zxWd_IGAtwIgds7DPiTvP8TfA',
    appId: '1:332395809937:ios:c50373ee825e501177c330',
    messagingSenderId: '332395809937',
    projectId: 'gossipapp-6c440',
    storageBucket: 'gossipapp-6c440.appspot.com',
    iosClientId: '332395809937-kipmd0184k7t7uj4vnlo76vuo89ksoa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gossipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ1YqMP2zxWd_IGAtwIgds7DPiTvP8TfA',
    appId: '1:332395809937:ios:c50373ee825e501177c330',
    messagingSenderId: '332395809937',
    projectId: 'gossipapp-6c440',
    storageBucket: 'gossipapp-6c440.appspot.com',
    iosClientId: '332395809937-kipmd0184k7t7uj4vnlo76vuo89ksoa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gossipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3JPBhyK31JXlVkA4qjKJCh9I7yCddCaU',
    appId: '1:332395809937:web:7c720217d56c687477c330',
    messagingSenderId: '332395809937',
    projectId: 'gossipapp-6c440',
    authDomain: 'gossipapp-6c440.firebaseapp.com',
    storageBucket: 'gossipapp-6c440.appspot.com',
    measurementId: 'G-4JDBWMLWH6',
  );
}
